contact: http://www.ucl.ac.uk/research-it-services/partner-with-us

title: UCL Research Programming Talks
includeleftnav: True
short: Programming Talks

crumbs:
  - {link: research-programming, text: Research Programming Hub}

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough","tables"]
