contact: http://www.ucl.ac.uk/research-it-services/partner-with-us

title: UCL Research Programming Talks
includeleftnav: True
short: Programming Talks

crumbs:
  - {link: 'http://www.ucl.ac.uk/rits', text: Research IT Services Hub}
  - {link: 'http://www.ucl.ac.uk/research-it-services/our-work/research-software-development', text: Research Software Development}

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough","tables"]
